PROGRAM (LEE) UNNAMED
          DESC, NO DESCRIPTION HAS BEEN WRITTEN.

          CHHZ, 19, B
          CONT, 101, B
          FADE, 19, 33, 120, B
          FADE, 33, 23, 73, B
          FADE, 23, 34, 267, B
          FADE, 34, 20, 62, B
          FADE, 20, 33, 191, B
          FADE, 33, 19, 90, B
          FADE, 19, 35, 193, B
          FADE, 35, 30, 293, B
          FADE, 30, 15, 8, B
          FADE, 15, 32, 191, B
          FADE, 32, 30, 11, B
END
